env:
  browser: true
  mocha: true
  cypress/globals: true
parserOptions:
  ecmaVersion: 2015
extends:
  - eslint:recommended
  - plugin:cypress/recommended
plugins:
  - cypress
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
